#!/usr/bin/with-contenv bash
echo "Hello from docker mods."

if [ -f /usr/bin/apt ]; then
    ## Ubuntu
    echo "\
        wget \
        terminator \
        rsync \
        ntp \
        nano \
        mousepad \
        unrar \
        unzip \
        xarchiver \
        mono-complete \
        libhunspell-dev \
        libmpv-dev \
        tesseract-ocr \
        vlc \
        ffmpeg \
        fonts-wqy-zenhei \
        language-pack-zh-hans \
        fzf \
        mediainfo \
        mediainfo-gui\
        compton" >> /mod-repo-packages-to-install.list
fi

chown -R root:root /root
# chmod -R 600 /root/.ssh
